### ISSUE TITLE
etrace throws error on using kernel events on Windows 7 x86

### ISSUE THREAD

**Issue by IL2** [goldshtn/etrace#4]
$ etrace --kernel Process

```
Unhandled Exception: System.InvalidOperationException: Can only use Kernel events in real time sessions on Windows 7 if you use TraceLog.CreateFromTraceEventSession
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.get_Source()
   at etrace.Program.RealTimeSession() in C:\projects\etrace\etrace\Program.cs:line 151
   at etrace.Program.Main(String[] args) in C:\projects\etrace\etrace\Program.cs:line 48
```

**Comment by goldshtn** [comment]
Thanks, that makes sense. I actually hadn't meant to support Windows 7. Would you like to take a look at fixing this and submit a PR? I think the exception message pretty much tells you what to do :-)

**Comment by IL2** [comment]
Sorry, I'm unqualified in C# and .NET. I guess that realtime monitor depends on some Win8+ feature as covered in [TraceLog example](https://github.com/Microsoft/dotnetsamples/blob/master/Microsoft.Diagnostics.Tracing/TraceEvent/TraceEvent/41_TraceLogMonitor.cs#L30) and I've missed the [comment](https://github.com/goldshtn/etrace/blob/master/etrace/Program.cs#L35) about it.
If it is not fixable, do not fix it :-)
